export const APP = {
  LOADING: 'LOADING',
  READY: 'READY'
};

export const LIST = {
  ADD_ITEM   : 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM'
};

export const USER = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED'
};